import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.backgroundLight },
  header: { paddingHorizontal: spacing.md, paddingTop: spacing.lg, paddingBottom: spacing.md },
  backLabel: { ...typography.caption, color: colors.olive },
  screenTitle: { ...typography.h2, marginTop: spacing.sm },
  scrollContent: { paddingHorizontal: spacing.md, paddingBottom: spacing.xxl },
  card: {
    borderRadius: 16,
    padding: spacing.lg,
    backgroundColor: colors.surfaceLight,
    shadowColor: colors.shadowSoft,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
    marginBottom: spacing.lg,
  },
  cardTitle: { ...typography.h3 },
  languageRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.md },
  rowDescription: { ...typography.body },
  fieldLabel: { ...typography.caption, color: colors.textSecondary, marginTop: spacing.md, marginBottom: spacing.xs },
  usernameRow: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center' },
  input: {
    ...typography.body,
    // iOS Safari zooms when focusing inputs smaller than 16px.
    fontSize: 16,
    flex: 1,
    minWidth: 0,
    borderWidth: 1,
    borderColor: colors.borderSoftLight,
    borderRadius: 10,
    backgroundColor: colors.surfaceMutedLight,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    color: colors.textPrimary,
  },
  readOnlyInput: {
    color: colors.textSecondary,
  },
  saveButton: { backgroundColor: colors.olive, borderRadius: 10, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  saveButtonSaving: { backgroundColor: colors.oliveLight },
  saveButtonLabel: { fontSize: 13, fontWeight: '600', color: colors.textPrimaryDark },
  actionRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    marginTop: spacing.md, paddingVertical: spacing.md, paddingHorizontal: spacing.md,
    backgroundColor: colors.surfaceMutedLight, borderRadius: 12,
  },
  actionLabel: { ...typography.body, color: colors.textPrimary, fontWeight: '500' },
  chevron: { fontSize: 22, lineHeight: 22, color: colors.textSecondary },
  dangerRow: { borderWidth: 1, borderColor: colors.danger + '55', backgroundColor: colors.danger + '0D' },
  dangerLabel: { ...typography.body, color: colors.danger, fontWeight: '600' },
  dangerChevron: { fontSize: 22, lineHeight: 22, color: colors.danger },
  buttonPressed: { opacity: 0.72 },
  buttonDisabled: { opacity: 0.5 },
  planHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  comingSoon: { ...typography.caption, color: colors.olive, fontWeight: '600' },
  planOptions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md },
  planOption: { flex: 1, borderWidth: 1, borderColor: colors.borderSoftLight, borderRadius: 12, padding: spacing.md, backgroundColor: colors.surfaceMutedLight },
  planOptionSelected: { borderColor: colors.olive, backgroundColor: colors.olive + '14' },
  planOptionDisabled: { opacity: 0.5 },
  planName: { ...typography.body, color: colors.textPrimary, fontWeight: '600', textAlign: 'center' },
});
